name: CI/CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Run Unit Tests
        run: |
          pnpm test:coverage
          echo "COVERAGE_SUMMARY=$(cat coverage/coverage-summary.json | jq -r tostring)" >> $GITHUB_ENV
        env:
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jest-coverage-report
          path: coverage/
          retention-days: 30

  Deploy-Preview:
    needs: Unit-Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: preview
        run: echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "${GITHUB_OUTPUT}"
    outputs:
      preview-url: ${{ steps.preview.outputs.url }}

  Comment-PR:
    needs: Deploy-Preview
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            üöÄ „Éó„É¨„Éì„É•„Éº„Éá„Éó„É≠„Ç§„ÅåÂÆå‰∫Ü„Åó„Åæ„Åó„ÅüÔºÅ -> ${{ needs.Deploy-Preview.outputs.preview-url }}
          comment_tag: preview-deployment
          mode: recreate

  Comment-Coverage:
    needs: Unit-Test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Comment Coverage Report
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## üìä „ÉÜ„Çπ„Éà„Ç´„Éê„É¨„ÉÉ„Ç∏„É¨„Éù„Éº„Éà

            ```json
            ${{ fromJson(env.COVERAGE_SUMMARY) }}
            ```
          comment_tag: coverage-report
          mode: recreate

  E2E-Test:
    needs: Deploy-Preview
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Install dependencies
        run: pnpm exec playwright install --with-deps
      - name: Run tests
        run: pnpm exec playwright test
        env:
          NODE_ENV: development
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
          BASE_URL: ${{ needs.Deploy-Preview.outputs.preview-url }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
